insert into paper_paper (id,name,description) values (1.0,'试卷1','试卷1');
insert into paper_question (id,serialno,content,paper_id) values (1.0,1.0,'认识你的人倾向形容你为： ',1.0);
insert into paper_question (id,serialno,content,paper_id) values (2.0,2.0,'下列哪一件事听起来比较吸引你？ ',1.0);
insert into paper_question (id,serialno,content,paper_id) values (3.0,3.0,'你倾向通过以下哪种方式收集信息：',1.0);
insert into paper_question (id,serialno,content,paper_id) values (4.0,4.0,'你把大部分和别人的相遇视为： ',1.0);
insert into paper_option (id,serialno,content,answer_type,question_id) values (1.0,'A','热情和敏感。','F',1.0);
insert into paper_option (id,serialno,content,answer_type,question_id) values (2.0,'B','逻辑和明确。','T',1.0);
insert into paper_option (id,serialno,content,answer_type,question_id) values (3.0,'A','与情人到有很多人且社交活动频繁的地方。','E',2.0);
insert into paper_option (id,serialno,content,answer_type,question_id) values (4.0,'B','呆在家中与情人做一些特别的事情，例如说观赏一部有趣的录影带并享用你最喜欢的外卖食物。','I',2.0);
insert into paper_option (id,serialno,content,answer_type,question_id) values (5.0,'A','你对有可能发生之事的想像和期望。','N',3.0);
insert into paper_option (id,serialno,content,answer_type,question_id) values (6.0,'B','你对目前状况的实际认知。','S',3.0);
insert into paper_option (id,serialno,content,answer_type,question_id) values (7.0,'A','友善及重要的。','E',4.0);
insert into paper_option (id,serialno,content,answer_type,question_id) values (8.0,'B','另有目的。','I',4.0);
insert into paper_report_template (id,name,description) values (1.0,'ISTJ','ISTJ');
insert into paper_report_paragraph_template (id,serialno,title,content,report_template_id) values (1.0,1.0,'标题1','内容1',1.0);
insert into paper_report_paragraph_template (id,serialno,title,content,report_template_id) values (2.0,2.0,'标题2','内容2',1.0);
insert into paper_report_paragraph_template (id,serialno,title,content,report_template_id) values (3.0,3.0,'标题3','内容3',1.0);
insert into paper_report_paragraph_template (id,serialno,title,content,report_template_id) values (4.0,4.0,'标题4','内容4',1.0);
